devices:
  sensor_1:
    name: "preheat"
    ip: "169.254.100.100"
    port: 502
    slave_id: 1
    registers:
      temperature: 360
    polling_interval: 20
    description: "Preheat temperature sensor for process monitoring (Fahrenheit)"
    
  sensor_2:
    name: "main_heat"
    ip: "169.254.100.200"
    port: 502
    slave_id: 1
    registers:
      temperature: 360
    polling_interval: 20
    description: "Main heat temperature sensor for primary monitoring (Fahrenheit)"
    
  sensor_3:
    name: "rib_heat"
    ip: "169.254.1.3"
    port: 502
    slave_id: 1
    registers:
      temperature: 360
    polling_interval: 20
    description: "Rib heat temperature sensor for secondary monitoring (Fahrenheit)" 